#!/usr/bin/env python3
"""The AUC is a property of the POOL, not of the signal. This script proves it.

WHY THIS EXISTS -- and the honest provenance, because it matters.

Two of our own analyses disagreed:

  * `a2_nfr.py` decomposed every flip against the qrels and found that **50.2% of all flips carry no
    relevance information at all** (wrong -> different-wrong, or relevant -> equally-relevant), and
    that flip ranks `ce_rerank` (the BEST variant, +5.1pp) as riskier than `churn_null_f25` (a
    deliberate null, -3.4pp). Conclusion: the signal is a distance, not a risk.
  * `analyze_miracl_risk2.py` reported flip-alone **AUC = 0.995**, beating the offline-gain ablation
    (0.943). Conclusion: the signal works.

Both cannot be right. This script found the reason, and the reason is the variant pool.

`analyze_miracl_risk2.py` evaluates on `real` variants and holds the churn nulls out to fit the
calibration curve. But the nulls are the ONLY HARMFUL VARIANTS THAT ARE NOT ON THE FUSION DIAL. Remove
them and the evaluation pool is 11 fusion-sweep variants (one method, one knob) plus 2 rerankers that
are both BENEFICIAL. There is then no harmful off-dial variant left, and the test cannot fail --
exactly the defect (item A2) that voided round 1, reintroduced through the back door.

On a monotone sweep, "distance from baseline" and "damage from baseline" are THE SAME QUANTITY. An AUC
computed there is a tautology. The hypothesis "flip predicts damage" is only *testable* on variants
that are not related to the baseline by a single monotone dial.

THE CRITERION (forced by the logic of the confound, not chosen to get an answer): flip rate is a
contribution iff, on the OFF-DIAL variants, it discriminates harmful from beneficial AND beats the
offline in-language gain -- a number you already have, for free, without computing any flip rate.

We disclose that this analysis was written AFTER seeing the 0.995, because the 0.995 contradicted the
NFR decomposition. We did not go looking for a way to kill the signal; we went looking for which of
our two answers was wrong.
"""
import argparse, json, os, sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provenance import stamp

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Declared in source. The partition is structural, not chosen by outcome:
# ON-DIAL  = variants generated by turning ONE knob (the dense/sparse fusion weight) from 1.0 to 0.0.
#            Flip and damage are both monotone in that knob BY CONSTRUCTION.
# OFF-DIAL = variants that are a different kind of intervention (a reranker; a pure-churn null).
ON_DIAL = ["native_ds_w0.98", "native_ds_w0.95", "native_ds_w0.90", "native_ds_w0.80", "native_sparse",
           "hybrid_dw0.95", "hybrid_dw0.90", "hybrid_dw0.70", "hybrid_dw0.50", "hybrid_dw0.30",
           "bm25_tuned"]
OFF_DIAL = ["ce_rerank", "colbert_rerank", "churn_null_f25", "churn_null_f50"]
BASE = "dense"
METRIC = "nDCG@10"


def auc(scores, labels):
    pos = [s for s, l in zip(scores, labels) if l]
    neg = [s for s, l in zip(scores, labels) if not l]
    if not pos or not neg:
        return float("nan")
    return sum((p > n) + 0.5 * (p == n) for p in pos for n in neg) / (len(pos) * len(neg))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-dir", default=os.path.join(REPO, "outputs/miracl2"))
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    out_path = a.out or os.path.join(a.in_dir, "pool_sensitivity.json")

    M = json.load(open(os.path.join(a.in_dir, "metrics.json")))
    langs = sorted(M)
    for L in langs:
        miss = [v for v in ON_DIAL + OFF_DIAL + [BASE] if v not in M[L]]
        if miss:
            raise SystemExit(f"{L} missing declared variants: {miss}")

    def dlt(L, v):
        return M[L][v][METRIC] - M[L][BASE][METRIC]

    # Signals are read off ONE calibration language; the label is damage on all the OTHERS.
    FLIP = lambda L, v: M[L][v]["flip_vs_dense"]      # the proposed signal
    GAIN = lambda L, v: -dlt(L, v)                    # the FREE baseline (in-language nDCG delta)

    def lolo(pool, score):
        per = []
        for L in langs:
            others = [o for o in langs if o != L]
            lab = [float(np.mean([dlt(o, v) for o in others])) < 0 for v in pool]
            sc = [score(L, v) for v in pool]
            x = auc(sc, lab)
            if x == x:
                per.append(x)
        return (float(np.mean(per)), float(np.std(per)), len(per)) if per else (float("nan"), 0.0, 0)

    pools = {
        "on_dial_only": ON_DIAL,
        "on_dial_plus_rerankers": ON_DIAL + ["ce_rerank", "colbert_rerank"],
        "full_pool": ON_DIAL + OFF_DIAL,
        "off_dial_only": OFF_DIAL,
    }
    res = {}
    for name, pool in pools.items():
        f_m, f_s, n = lolo(pool, FLIP)
        g_m, g_s, _ = lolo(pool, GAIN)
        res[name] = {"n_variants": len(pool), "n_folds": n,
                     "flip_auc": f_m, "flip_sd": f_s,
                     "offline_gain_auc": g_m, "offline_gain_sd": g_s,
                     "flip_minus_gain": f_m - g_m}

    # The decisive pair: two variants whose flip rates are indistinguishable and whose outcomes are not.
    pair = {}
    for v in ("colbert_rerank", "churn_null_f25"):
        pair[v] = {"flip": float(np.mean([FLIP(L, v) for L in langs])),
                   "dndcg": float(np.mean([dlt(L, v) for L in langs]))}
    pair["flip_gap"] = abs(pair["colbert_rerank"]["flip"] - pair["churn_null_f25"]["flip"])
    pair["outcome_gap"] = abs(pair["colbert_rerank"]["dndcg"] - pair["churn_null_f25"]["dndcg"])

    verdict = ("DEAD" if res["off_dial_only"]["flip_auc"] <= res["off_dial_only"]["offline_gain_auc"]
               else "SURVIVES")
    out = {"languages": langs, "on_dial": ON_DIAL, "off_dial": OFF_DIAL,
           "pools": res, "decisive_pair": pair, "verdict": verdict}
    json.dump(stamp(out, "a2_pool_sensitivity.py"), open(out_path, "w"), indent=2)

    print("Predicting OOD regression. Higher score = predicted riskier. LOLO over calibration language.\n")
    print(f"  {'pool':44s} {'n':>3s} {'FLIP':>7s} {'OFFLINE GAIN (free)':>21s}")
    for name in ("on_dial_only", "on_dial_plus_rerankers", "full_pool", "off_dial_only"):
        r = res[name]
        star = "   <-- the only honest test" if name == "off_dial_only" else ""
        print(f"  {name:44s} {r['n_variants']:3d} {r['flip_auc']:7.3f} "
              f"{r['offline_gain_auc']:21.3f}{star}")
    print("\n  On ONE MONOTONE DIAL, distance-from-baseline and damage-from-baseline are the SAME")
    print("  QUANTITY. An AUC computed there is arithmetic, not evidence. That pool -- and only that")
    print("  pool -- is what produced round 1's AUC = 1.000.\n")
    c, n = pair["colbert_rerank"], pair["churn_null_f25"]
    print(f"  The decisive pair:")
    print(f"    colbert_rerank  flip={c['flip']:.3f}   dNDCG={c['dndcg']:+.4f}  (GOOD)")
    print(f"    churn_null_f25  flip={n['flip']:.3f}   dNDCG={n['dndcg']:+.4f}  (HARMFUL, by construction)")
    print(f"    flip rates differ by {pair['flip_gap']:.4f}; outcomes differ by {pair['outcome_gap']:.4f}.")
    print(f"    Flip cannot separate them EVEN IN PRINCIPLE.\n")
    print(f"  VERDICT: flip is {verdict}. Off the dial the FREE baseline scores "
          f"{res['off_dial_only']['offline_gain_auc']:.3f} and flip scores "
          f"{res['off_dial_only']['flip_auc']:.3f}.")
    print(f"[saved] {out_path}")


if __name__ == "__main__":
    main()
